In [1]:
import pandas as pd

In [2]:
train_rides_df = pd.read_csv('DBtrainrides.csv')

In [3]:
train_rides_df.head()

ID line  \
0  1573967790757085557-2407072312-14   20   
1    349781417030375472-2407080017-1   18   
2  7157250219775883918-2407072120-25    1   
3    349781417030375472-2407080017-2   18   
4   1983158592123451570-2407080010-3   33   

                                                path   eva_nr  category  \
0  Stolberg(Rheinl)Hbf Gl.44|Eschweiler-St.Jöris|...  8000001         2   
1                                                NaN  8000001         2   
2  Hamm(Westf)Hbf|Kamen|Kamen-Methler|Dortmund-Ku...  8000406         4   
3                                         Aachen Hbf  8000404         5   
4                            Herzogenrath|Kohlscheid  8000404         5   

             station                state    city    zip      long        lat  \
0         Aachen Hbf  Nordrhein-Westfalen  Aachen  52064  6.091499  50.767800   
1         Aachen Hbf  Nordrhein-Westfalen  Aachen  52064  6.091499  50.767800   
2  Aachen-Rothe Erde  Nordrhein-Westfalen  Aachen  52066  6.116475  50.770202   
3        Aachen West  Nordrhein-Westfalen  Aachen  52072  6.070715  50.780360   
4        Aachen West  Nordrhein-Westfalen  Aachen  52072  6.070715  50.780360   

          arrival_plan       departure_plan       arrival_change  \
0  2024-07-08 00:00:00  2024-07-08 00:01:00  2024-07-08 00:03:00   
1                  NaN  2024-07-08 00:17:00                  NaN   
2  2024-07-08 00:03:00  2024-07-08 00:04:00  2024-07-08 00:03:00   
3  2024-07-08 00:20:00  2024-07-08 00:21:00                  NaN   
4  2024-07-08 00:20:00  2024-07-08 00:21:00  2024-07-08 00:20:00   

      departure_change  arrival_delay_m  departure_delay_m info  \
0  2024-07-08 00:04:00                3                  3  NaN   
1                  NaN                0                  0  NaN   
2  2024-07-08 00:04:00                0                  0  NaN   
3                  NaN                0                  0  NaN   
4  2024-07-08 00:21:00                0                  0  NaN   

  arrival_delay_check departure_delay_check  
0             on_time               on_time  
1             on_time               on_time  
2             on_time               on_time  
3             on_time               on_time  
4             on_time               on_time

In [4]:
train_rides_df.count()

ID                       2061357
line                     2061357
path                     1850002
eva_nr                   2061357
category                 2061357
station                  2061357
state                    2061357
city                     2061357
zip                      2061357
long                     2061357
lat                      2061357
arrival_plan             1850002
departure_plan           2061357
arrival_change           1585727
departure_change         1721431
arrival_delay_m          2061357
departure_delay_m        2061357
info                      645341
arrival_delay_check      2061357
departure_delay_check    2061357
dtype: int64

2,061,357–1,850,002 = 211,355 fewer cases in the 'path' column

In [5]:
# Step 2: Create a new DataFrame with a count of how often each 'eva_nr' is mentioned
station_mapping_df = train_rides_df.groupby(['eva_nr', 'station', 'category', 'city']).size().reset_index(name='count')

# Step 3: Optionally, reset the index for a cleaner DataFrame
station_mapping_df = station_mapping_df.reset_index(drop=True)

# Display the new DataFrame
station_mapping_df

eva_nr              station  category        city  count
0     8000001           Aachen Hbf         2      Aachen   1488
1     8000002            Aalen Hbf         3       Aalen    823
2     8000004           Altenbeken         3  Altenbeken    848
3     8000007                Alzey         3       Alzey    591
4     8000009              Ansbach         3     Ansbach    829
...       ...                  ...       ...         ...    ...
1991  8089472     Lichterfelde Süd         5      Berlin   1544
1992  8089473       Osdorferstraße         5      Berlin   1536
1993  8089474           Schöneberg         4      Berlin   5831
1994  8089537  Julius-Leber-Brücke         5      Berlin   2191
1995  8098360      Bürstadt (Ried)         5    Bürstadt    534

[1996 rows x 5 columns]

In [8]:
station_mapping_df.count()

eva_nr      1996
station     1996
category    1996
city        1996
count       1996
dtype: int64

what is the average number of stations per category? go check the 'category' column

In [6]:
# Step 1: Split the 'path' into individual stations where 'path' is not empty
# Create a new DataFrame that splits the 'path' column
stations_df = train_rides_df['path'].str.split('|', expand=True)

# Step 2: Keep the same 'eva_nr', 'station', and 'city' columns, add the split station columns
split_stations_df = pd.concat([train_rides_df[['eva_nr', 'station', 'city']], stations_df], axis=1)

split_stations_df

eva_nr                        station        city  \
0        8000001                     Aachen Hbf      Aachen   
1        8000001                     Aachen Hbf      Aachen   
2        8000406              Aachen-Rothe Erde      Aachen   
3        8000404                    Aachen West      Aachen   
4        8000404                    Aachen West      Aachen   
...          ...                            ...         ...   
2061352  8002795                 Herten (Westf)      Herten   
2061353  8003775                Lübeck-Moisling      Lübeck   
2061354  8003775                Lübeck-Moisling      Lübeck   
2061355  8001580  Düsseldorf Flughafen Terminal  Düsseldorf   
2061356  8001580  Düsseldorf Flughafen Terminal  Düsseldorf   

                                 0                        1  \
0        Stolberg(Rheinl)Hbf Gl.44      Eschweiler-St.Jöris   
1                              NaN                      NaN   
2                   Hamm(Westf)Hbf                    Kamen   
3                       Aachen Hbf                     None   
4                     Herzogenrath               Kohlscheid   
...                            ...                      ...   
2061352                Bottrop Hbf              Bottrop-Boy   
2061353   Lübeck-Travemünde Strand  Lübeck-Travemünde Hafen   
2061354               Bad Oldesloe          Reinfeld(Holst)   
2061355                        NaN                      NaN   
2061356                        NaN                      NaN   

                                      2                  3  \
0                    Alsdorf Poststraße  Alsdorf-Mariadorf   
1                                   NaN                NaN   
2                         Kamen-Methler      Dortmund-Kurl   
3                                  None               None   
4                                  None               None   
...                                 ...                ...   
2061352                   Gladbeck West               None   
2061353  Lübeck-Travem. Skandinavienkai    Lübeck-Kücknitz   
2061354                            None               None   
2061355                             NaN                NaN   
2061356                             NaN                NaN   

                               4                 5              6  ...    49  \
0            Alsdorf-Kellersberg  Alsdorf-Annapark  Alsdorf-Busch  ...  None   
1                            NaN               NaN            NaN  ...  None   
2           Dortmund-Scharnhorst      Dortmund Hbf     Bochum Hbf  ...  None   
3                           None              None           None  ...  None   
4                           None              None           None  ...  None   
...                          ...               ...            ...  ...   ...   
2061352                     None              None           None  ...  None   
2061353  Lübeck-Dänischburg IKEA        Lübeck Hbf           None  ...  None   
2061354                     None              None           None  ...  None   
2061355                      NaN               NaN            NaN  ...  None   
2061356                      NaN               NaN            NaN  ...  None   

           50    51    52    53    54    55    56    57    58  
0        None  None  None  None  None  None  None  None  None  
1        None  None  None  None  None  None  None  None  None  
2        None  None  None  None  None  None  None  None  None  
3        None  None  None  None  None  None  None  None  None  
4        None  None  None  None  None  None  None  None  None  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...  
2061352  None  None  None  None  None  None  None  None  None  
2061353  None  None  None  None  None  None  None  None  None  
2061354  None  None  None  None  None  None  None  None  None  
2061355  None  None  None  None  None  None  None  None  None  
2061356  None  None  None  None  None  None  None  None  None  

[2061357 rows x 62 co

In [7]:
split_stations_df.head()

eva_nr            station    city                          0  \
0  8000001         Aachen Hbf  Aachen  Stolberg(Rheinl)Hbf Gl.44   
1  8000001         Aachen Hbf  Aachen                        NaN   
2  8000406  Aachen-Rothe Erde  Aachen             Hamm(Westf)Hbf   
3  8000404        Aachen West  Aachen                 Aachen Hbf   
4  8000404        Aachen West  Aachen               Herzogenrath   

                     1                   2                  3  \
0  Eschweiler-St.Jöris  Alsdorf Poststraße  Alsdorf-Mariadorf   
1                  NaN                 NaN                NaN   
2                Kamen       Kamen-Methler      Dortmund-Kurl   
3                 None                None               None   
4           Kohlscheid                None               None   

                      4                 5              6  ...    49    50  \
0   Alsdorf-Kellersberg  Alsdorf-Annapark  Alsdorf-Busch  ...  None  None   
1                   NaN               NaN            NaN  ...   NaN   NaN   
2  Dortmund-Scharnhorst      Dortmund Hbf     Bochum Hbf  ...  None  None   
3                  None              None           None  ...  None  None   
4                  None              None           None  ...  None  None   

     51    52    53    54    55    56    57    58  
0  None  None  None  None  None  None  None  None  
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2  None  None  None  None  None  None  None  None  
3  None  None  None  None  None  None  None  None  
4  None  None  None  None  None  None  None  None  

[5 rows x 62 columns]

Visualise the stations in a map (/grid) (without it being mapped in a real map) and see if there are any patterns. George, Additionally, uses the same map to see the delay (in % of total rides) per station. George
See if we can use K-means to cluster the stations into mini regions to see if the entire region has delay problems. We do not know what k to use, so we can try a few values. Check the distance per stations and see by eye if the clusters make sense to create. Raphael